#!/usr/bin/env python3
"""Derives the aarch64 syscalls NOT allowed by Android's app seccomp filter.

Inputs: third_party/aosp-bionic-seccomp/*.TXT (AOSP policy sources) and an
asm-generic/unistd.h for name -> number. Output: a C++ header with a constexpr
predicate, used by the local FEX patch to return -ENOSYS instead of letting a
passthrough syscall die with SIGSYS.

Usage: gen-android-seccomp.py <aosp-dir> <unistd.h> [cpp|c] > header
  cpp (default): constexpr FEXDroid::IsTrappedOnAndroid(), for the FEX patch
  c:             static inline fxd_android_trapped(), for the glibc patch
"""
import re, sys

aosp, unistd = sys.argv[1:3]
flavor = sys.argv[3] if len(sys.argv) > 3 else 'cpp'

def parse(path):
    out = set()
    for line in open(path):
        line = line.split('#')[0].strip()
        if not line or '(' not in line:
            continue
        head = line.split('(')[0].strip()
        arches = line.rsplit(')', 1)[-1].strip()
        if arches and not any(a in arches.split(',') for a in ('all', 'arm64', 'lp64')):
            continue
        fn = head.split()[-1]
        sc = fn.split(':', 1)[1] if ':' in fn else fn
        out.add(sc.split('|')[0].split(',')[0].strip())
    return out

import glob, os

def allowed_in(d):
    """Syscalls one Android release's app policy allows (allow/whitelist minus block/blacklist)."""
    allow = parse(f'{d}/SYSCALLS.TXT')
    for f in glob.glob(f'{d}/SECCOMP_*.TXT'):
        name = os.path.basename(f)
        if 'ALLOWLIST' in name or 'WHITELIST' in name:
            allow |= parse(f)
    for f in glob.glob(f'{d}/SECCOMP_*.TXT'):
        name = os.path.basename(f)
        if 'BLOCKLIST' in name or 'BLACKLIST' in name:
            allow -= parse(f)
    return allow

# One subdirectory per Android release; a syscall counts as allowed only if every
# release allows it (e.g. clone3 is allowed since Android 15, trapped on 14).
releases = sorted(d for d in glob.glob(f'{aosp}/*') if os.path.isdir(d))
if not releases:
    releases = [aosp]
allowed = set.intersection(*(allowed_in(d) for d in releases))

# number -> every name asm-generic gives it (e.g. 84 = sync_file_range / sync_file_range2).
names_by_nr = {}
for line in open(unistd):
    m = re.match(r'#define __NR(?:3264)?_(\w+)\s+(\d+)\s*$', line)
    if not m:
        continue
    name, nr = m.group(1), int(m.group(2))
    if name == 'syscalls' or name.endswith('_time64') or name == 'arch_specific_syscall' \
            or 403 <= nr <= 423:  # 32-bit-only y2038 syscalls, unused on arm64
        continue  # counter, 32-bit-only time64 calls, reserved arch range
    names_by_nr.setdefault(nr, set()).add(name)
# __NR3264_fstatat is newfstatat on 64-bit architectures.
names_by_nr.setdefault(79, set()).add('newfstatat')

# Trapped calls that must report success instead of ENOSYS: the identity-changing
# family. An Android app is never root, so these can only ever be no-ops (e.g.
# Xvfb's child does setgid(getgid()); setuid(getuid()) before exec and exits on
# failure). Nothing is granted: the real syscall never reaches the kernel.
FAKE_SUCCESS_NAMES = {'setuid', 'setgid', 'setreuid', 'setregid', 'setresuid', 'setresgid',
                      'setfsuid', 'setfsgid', 'setgroups'}

trapped = sorted((nr, '/'.join(sorted(n))) for nr, n in names_by_nr.items()
                 if not (n & allowed))
print('/* Generated by scripts/lib/gen-android-seccomp.py from AOSP bionic policy files')
print('   (' + ', '.join(os.path.basename(r) for r in releases) + ').')
print('   aarch64 syscalls some Android release\'s untrusted_app seccomp filter traps (SIGSYS).  */')
print('#pragma once\n')
fake = [nr for nr, name in trapped if set(name.split('/')) & FAKE_SUCCESS_NAMES]
if flavor == 'cpp':
    print('namespace FEXDroid {\nconstexpr bool IsTrappedOnAndroid(int nr) {\n  switch (nr) {')
    for nr, name in trapped:
        print(f'  case {nr}: // {name}')
    print('    return true;\n  default:\n    return false;\n  }\n}')
    print('// Trapped identity-changing calls answered with success (the app is never root).')
    print('constexpr bool IsFakeSuccessOnAndroid(int nr) {\n  switch (nr) {')
    for nr in fake:
        print(f'  case {nr}:')
    print('    return true;\n  default:\n    return false;\n  }\n}\n} // namespace FEXDroid')
else:
    # Assembler: FXD_SVC replaces "mov x8, NR; svc 0" in glibc's DO_CALL.
    print('#ifdef __ASSEMBLER__')
    print('.macro FXD_SVC nr')
    fcond = ' || '.join(f'(\\nr == {nr})' for nr in fake)
    cond = ' || '.join(f'(\\nr == {nr})' for nr, _ in trapped)
    print(f'.if {fcond}')
    print('\tmov x0, #0 /* identity change: no-op success (app is never root) */')
    print(f'.elseif {cond}')
    print('\tmov x0, #-38 /* -ENOSYS: trapped by Android seccomp */')
    print('.else')
    print('\tmov x8, \\nr')
    print('\tsvc 0')
    print('.endif')
    print('.endm')
    print('#else')
    print('static inline int\nfxd_android_trapped (long int nr)\n{\n  switch (nr)\n    {')
    for nr, name in trapped:
        print(f'    case {nr}: /* {name} */')
    print('      return 1;\n    default:\n      return 0;\n    }\n}')
    print('\n/* Trapped calls answered with success (see FAKE_SUCCESS_NAMES).  */')
    print('static inline int\nfxd_android_fake_success (long int nr)\n{\n  switch (nr)\n    {')
    for nr in fake:
        print(f'    case {nr}:')
    print('      return 1;\n    default:\n      return 0;\n    }\n}')
    print('#endif')
